### ISSUE TITLE
Determining Client is active ?

### ISSUE THREAD

**Issue by saitejar** [kishore-narendran/crdt-py#2]
How to determine if a client is inactive, i.e he might have created a crdt instance and then exited the program..

**Comment by kishore-narendran** [comment]
That is not a concern, if the client does not use a CRDT, it will merely live in Redis, and not be accessed. If we want to collect such garbage CRDTs which have been created and not used, we can periodically go and delete the CRDT instance.

**Comment by saitejar** [comment]
okay.. we can do it passively, through garbage collection...
