### ISSUE TITLE
persistent data structure ?

### ISSUE THREAD

**Issue by saitejar** [kishore-narendran/crdt-py#3]
Should we allow a way for  client to indicate that he wants the data structure to persist even after it exits, so wen it comes back, it can access it with some key or id ?

**Comment by kishore-narendran** [comment]
I was thinking it can always persist. And only be deleted if it is explicitly deleted by one of the clients.

**Comment by saitejar** [comment]
this and the other comment are contradictory kind of, if it persists, then there should be a guarantee, as we will do garbage collection, there won't be a guarantee that it ll persist.

**Comment by kishore-narendran** [comment]
What I wanted to say is that, it is a choice. We can place a guarantee up to a certain limit.

**Comment by saitejar** [comment]
if the client wants it to persist for sure, he shd state so ? otherwise, no guarantee.

**Comment by saitejar** [comment]
hmm... even then there shd be some time to live.. we shdnt have it forever.. may be

**Comment by saitejar** [comment]
actly, lets not worry abt it now.. we can think of this later also

**Comment by kishore-narendran** [comment]
Okay, maybe we will build in whether it should persist. If not, by default, we give a standard guarantee of some `x hours` or `x days`.
